import = [
	"/home/jaykee/.config/alacritty/themes/alacritty-master/dracula.toml"
]

[window]

opacity = 0.9 

padding.x = 10
padding.y = 10


[font]

size = 9.0


[cursor]
style.blinking = "Always"
blink_timeout= 0
